language: java

jdk:
  - oraclejdk8

notifications:
  email: false

branches:
  except:
    - gh-pages

before_install:
  - export TERM=dumb
  - sudo apt-get update
  - sudo apt-get install -qq libstdc++6:i386 lib32z1

install:
  - TERM=dumb ./gradlew assembleDebug

script:
  - TERM=dumb ./gradlew checkDebug